
% -------------------------------------------------------------------------
% export_mesh_data.m
% -------------------------------------------------------------------------
% Renamed from 'export' to avoid conflicts with MATLAB built-in functions.
% Reads the Abaqus .inp generated by make_mesh_3pb.py and saves .txt files.
% -------------------------------------------------------------------------

function export_mesh_data(inpFile, outFolder)

    clc;

    % 1. Locate the .inp file
    if nargin < 1 || isempty(inpFile)
        hits = dir('Gregoire_3PB/*.inp'); % Look in the folder created by Python
        if isempty(hits)
            hits = dir('*.inp');
        end
        if isempty(hits)
            error('No .inp file found. Run your Python script first or provide path.');
        end
        inpFile = fullfile(hits(1).folder, hits(1).name);
    end

    % 2. Set output folder (match the directory used in solver_main_3pb.m)
    if nargin < 2 || isempty(outFolder)
        outFolder = 'Gregoire_3PB';
    end

    if ~exist(outFolder, 'dir')
        mkdir(outFolder);
    end

    fprintf('Processing: %s\n', inpFile);

    % 3. Run the extraction logic
    try
        perform_extraction(inpFile, outFolder);
        fprintf('Success! Files written to %s/\n', outFolder);
    catch ME
        fprintf('Error during extraction: %s\n', ME.message);
    end

end

function perform_extraction(inpFile, outFolder)
    fid = fopen(inpFile, 'r');
    if fid == -1, error('File not found.'); end
    C = textscan(fid, '%s', 'Delimiter', '\n', 'Whitespace', '');
    fclose(fid);
    lines = C{1};

    % Storage for data
    nodes = [];
    elems = [];
    sets = struct('Load_Nodes',[],'Support_Left',[],'Support_Right',[],'CMOD1',[],'CMOD2',[]);
    bc_data = {};

    i = 1;
    while i <= numel(lines)
        line = strtrim(lines{i});
        low = lower(line);

        % Parse *NODE
        if startsWith(low, '*node') && ~contains(low, 'output')
            i = i + 1;
            while i <= numel(lines) && ~startsWith(lines{i}, '*')
                v = sscanf(strrep(lines{i}, ',', ' '), '%f');
                if numel(v) >= 3
                    nodes = [nodes; v(1:3)']; %#ok<AGROW>
                end
                i = i + 1;
            end
            continue;
        end

        % Parse *ELEMENT (specifically CPS3 triangles)
        if startsWith(low, '*element') && ~contains(low, 'output')
            i = i + 1;
            while i <= numel(lines) && ~startsWith(lines{i}, '*')
                v = sscanf(strrep(lines{i}, ',', ' '), '%f');
                if numel(v) >= 4
                    elems = [elems; v(1:4)']; %#ok<AGROW>
                end
                i = i + 1;
            end
            continue;
        end

        % Parse *NSET
        if startsWith(low, '*nset')
            nsetName = extract_val(line, 'nset');
            isGen = contains(low, 'generate');
            i = i + 1;
            acc = [];
            while i <= numel(lines) && ~startsWith(lines{i}, '*')
                v = sscanf(strrep(lines{i}, ',', ' '), '%f')';
                if isGen
                    for g = 1:3:numel(v)
                        acc = [acc, v(g):v(g+2):v(g+1)]; %#ok<AGROW>
                    end
                else
                    acc = [acc, v]; %#ok<AGROW>
                end
                i = i + 1;
            end
            
            % Assign to specific sets if name matches
            fn = fieldnames(sets);
            for f = 1:numel(fn)
                if strcmpi(nsetName, fn{f})
                    sets.(fn{f}) = unique([sets.(fn{f}), acc]);
                end
            end
            continue;
        end
        
        % Parse *BOUNDARY
        if startsWith(low, '*boundary')
            i = i + 1;
            while i <= numel(lines) && ~startsWith(lines{i}, '*')
                pts = strsplit(strtrim(lines{i}), ',');
                if numel(pts) >= 3
                    val = 0;
                    if numel(pts) >= 4, val = str2double(pts{4}); end
                    bc_data{end+1} = {str2double(pts{2}), str2double(pts{3}), val}; %#ok<AGROW>
                end
                i = i + 1;
            end
            continue;
        end
        i = i + 1;
    end

    % --- Deduplicate Nodes (Abaqus often repeats nodes for Reference Points) ---
    [~, idx] = unique(nodes(:,1), 'first');
    nodes = nodes(idx, :);

    % --- Save outputs in simple text format ---
    writemtx(fullfile(outFolder, 'nodes.txt'), nodes, '%d %.6f %.6f');
    writemtx(fullfile(outFolder, 'elements.txt'), elems, '%d %d %d %d');
    
    writeids(fullfile(outFolder, 'top_nodes.txt'), sets.Load_Nodes);
    writeids(fullfile(outFolder, 'left_nodes.txt'), sets.Support_Left);
    writeids(fullfile(outFolder, 'right_nodes.txt'), sets.Support_Right);
    
    % Solver expects single node IDs for CMOD control
    writeids(fullfile(outFolder, 'cmod1.txt'), min(sets.CMOD1));
    writeids(fullfile(outFolder, 'cmod2.txt'), max(sets.CMOD2));

    % Save BCs
    fid = fopen(fullfile(outFolder, 'boundary_conditions.txt'), 'w');
    for b = 1:numel(bc_data)
        fprintf(fid, '%d %d %.6f\n', bc_data{b}{1}, bc_data{b}{2}, bc_data{b}{3});
    end
    fclose(fid);
end

% Helpers
function v = extract_val(line, param)
    v = '';
    t = regexp(line, [param ' *= *([^, ]+)'], 'tokens');
    if ~isempty(t), v = t{1}{1}; end
end

function writemtx(path, M, fmt)
    fid = fopen(path, 'w');
    if ~isempty(M), fprintf(fid, [fmt '\n'], M'); end
    fclose(fid);
end

function writeids(path, ids)
    fid = fopen(path, 'w');
    if ~isempty(ids), fprintf(fid, '%d\n', ids); end
    fclose(fid);
end